language: c
sudo: required
before_install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
install: bash -ex .travis-opam.sh && bash -ex .travis-ci.sh
script: bash-ex .travis-ci2.sh
env:
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
os:
  - linux
  - osx
