FROM ocaml/opam2:ubuntu
CMD /bin/bash

ENV OPAMYES true
RUN sudo apt-get -yq install cmake m4 pkg-config libffi-dev

RUN sudo useradd -ms /bin/bash mammut && echo "mammut:mammut" | sudo chpasswd && sudo adduser mammut sudo
USER mammut
WORKDIR /home/mammut
CMD /bin/bash

USER root

# install opam dependencies
RUN opam install ctypes ctypes-foreign ocamlfind

# copy and compile test
CMD mkdir ocaml_mammut && cd ocaml_mammut
ADD . .

RUN eval $(opam env)  && make && make test

#need msr (modprobe msr) to run the test
